version: '2.0'
services:
  notebooks_base:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "com.donkeycar=notebooks"
  notebooks_run:
    extends:
      service: notebooks_base
    ports:
      - "8888:8888"
    volumes:
      - .:/notebooks
      - ../donkeybarn:/app/src/donkeybarn
    tty: true
    stdin_open: true