version: '2.3'
services:
  notebooks_base:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "com.donkeycar=notebooks"
  notebooks_run:
    extends:
      service: notebooks_base
    ports:
      - "8888:8888"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/notebooks
      - ~/.donkey_data:/root/.donkey_data
      #load local repos for developement here.
      - ../donkeybarn:/opt/src/donkeybarn
      - ~/data/:/root/data
    tty: true
    stdin_open: true